#!/usr/bin/env bash

pushd ~/personal/dev-env/env/.config/nvim
git add .
git commit -m 'automated dev commit'
git push
popd

pushd ~/personal/dev-env
git add .
git commit -m 'automated dev commit'
git push
popd
