#!/usr/bin/env bash

sudo dnf -y install ninja-build cmake gcc make unzip gettext curl
git clone https://github.com/neovim/neovim.git $HOME/personal/neovim
pushd $HOME/personal/neovim
git checkout stable

make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
popd
