#!/usr/bin/env bash

sudo dnf install nodejs npm -y

echo "------------ Installing N ----------"

npm i -g n
# make cache folder (if missing) and take ownership
sudo mkdir -p /usr/local/n
sudo chown -R $(whoami) /usr/local/n
# make sure the required folders exist (safe to execute even if they already exist)
sudo mkdir -p /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
# take ownership of Node.js install destination folders
sudo chown -R $(whoami) /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share

n lts

echo "------------ Installing BUN ----------"

curl -fsSL https://bun.sh/install | bash
