
[env]
TERM = "xterm-256color"

[font]
size = 14
  [font.normal]
  family = "JetBrains Mono NerdFont"
  style = "Medium"

  [font.bold]
  family = "JetBrains Mono NerdFont"
  style = "Heavy"

  [font.bold_italic]
  family = "JetBrains Mono NerdFont"
  style = "Heavy Italic"

  [font.italic]
  family = "JetBrains Mono NerdFont"
  style = "Medium Italic"

[general]
live_config_reload = true
